# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37ffb2db17d790769fecf780f2d03add70996b241eb776e898f520d06b24de631ce0200447b1c6978ee23595d2aec6e13ba3f91826526625e4d0d5d9583894c3

test:
  secret_key_base: ba9eaf833bcfb240aa955b2a33397de8fa4b3e5def22867b15db0009868b79dd58a53973e4b21b62a3b9c8deb04628fd577e773f55f0c8e6d6145ac645464357

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
